### ISSUE TITLE
Does this approach need the camera parameters?

### ISSUE THREAD

**Issue by Remember2018** [kunzmi/ImageStackAlignator#21]
Hi @kunzmi , I  found that in your code, there is a file named `ExtraCameraProfiles.xml` to get the camera profiles.
Is this a necessity for this approach? 

If we just have several images without the camera parameters, is this method still suitable for their multi-frame super-resolution?

**Comment by kunzmi** [comment]
You need the noise model parameters, otherwise the algorithm cannot guess if a patch is just noisy flat signal or some actual feature. Some DNG files already have these values stored, some don't, in which case you need the ```ExtraCameraProfiles.xml```. If you open a file and some values appear for ```Noise model alpha``` you should be good.

**Comment by Remember2018** [comment]
Hi, @kunzmi , thanks a lot for your kind comment! It is possible that first convert the multi-frame RGB images back to PEF files under some-certain camera model (e.g., the camera in your code), then adopt your code to conduct the multi-frame super-resolution? 
Given the multi-frame RGB images, their bayer pattern parameters are missing. So I'm not sure if this is a possible solution to use your code in the ordinal multi-frame RGB images for their super-resolution.

Currently I'm trying to use the `TestMode` in your code. And replace the randomly generated image in your code to a given RGB image (the RGB image is first converted to its grayscale image, and as the `frame1` to fit the `TestRawFile`, the other frames are generated as shown in your code). The parameters are set as your noted in the `README.md`. But it seems the final result seems have problems. 

If convenient, could you please help give some advice? Thanks.

![frame1](https://user-images.githubusercontent.com/43327429/113265722-0ef62a80-9307-11eb-80a0-e09bde084b29.png)
![frame2](https://user-images.githubusercontent.com/43327429/113265732-10bfee00-9307-11eb-8d09-84c60cc256b5.png)
![frame3](https://user-images.githubusercontent.com/43327429/113265737-11588480-9307-11eb-8007-a94f3d293920.png)
![frame4](https://user-images.githubusercontent.com/43327429/113265741-11f11b00-9307-11eb-9111-c352311b07e3.png)
![frame5](https://user-images.githubusercontent.com/43327429/113265745-1289b180-9307-11eb-8451-25f372cbae83.png)
![pre-align](https://user-images.githubusercontent.com/43327429/113265759-1584a200-9307-11eb-82fe-87024f2eaf1e.png)
![patches2](https://user-images.githubusercontent.com/43327429/113265748-13224800-9307-11eb-9d05-1100ea7a5a4e.png)
![patches3](https://user-images.githubusercontent.com/43327429/113265751-14537500-9307-11eb-971b-b5ad92308e49.png)
![patches4](https://user-images.githubusercontent.com/43327429/113265757-14ec0b80-9307-11eb-8cac-5715b7790412.png)
![patches5](https://user-images.githubusercontent.com/43327429/113265758-14ec0b80-9307-11eb-9f9d-4d48b0d81691.png)
![accumulate](https://user-images.githubusercontent.com/43327429/113265746-13224800-9307-11eb-9a29-145428384720.png)

**Comment by kunzmi** [comment]
Hi,
The original paper and this code are meant to debayer RAW images and additionally get super-resolution, whereas it is for sure possible to only use the super-resolution part, it is not usable as is without adaptions. So in case you already have all three color planes, you'd need to adapt the code and skip all debayering steps (and add file/image support for your images). In my eyes it doesn't make sense to try out super-resolution by first reducing the resolution by applying a bayer-pattern, so recreating a PEF file wouldn't make much sense here...

**Comment by Remember2018** [comment]
Hi, @kunzmi , thanks a lot for your suggestion!
