### ISSUE TITLE
Is it possible to run the code in Ubuntu?

### ISSUE THREAD

**Issue by Remember2018** [kunzmi/ImageStackAlignator#22]
Hi @kunzmi , your great code was implemented using `C#`. I found that Microsoft has provided the `C#` or `.NET` runtime library running in Ubuntu. 

My question is, can the `ManagedCUDA` and the code in this repository be run in Ubuntu with that .NET SDKs? Have you tried to run the code in Ubuntu? Would it be slow to run the code using .NET framework? 

Your `ManagedCUDA` has packaged many low-level CUDA functions. Is there an alternative using C++? 
I found that, if I need to convert the `ManagedCUDA` to its C++ version, that would be a huge project for me.

If convenient, could you please give some advice? Thanks.

**Comment by kunzmi** [comment]
The only restricition is the GUI because WPF doesn't run on Linux (maybe with Wine but I never tried). The main code itself runs perfectly fine also on Linux, managedCuda is made for that (.netCore and older mono). You can run the same code on Windows and Linux :) 
So if you can live without GUI, just get rid of it and let the rest run as it is.

**Comment by Remember2018** [comment]
Hi @kunzmi , thanks a lot for your kind comments and suggestions!

In fact, I need to figure out a solution on multi frame super resolution in a NVIDIA Jetson Xavier NX board, which is an ARM-cpu with nvidia gpu. The inputs are some images for the same scene but with some affine transformations. The output is a high-resolution image. 
I checked your great code and several deep learning based MFSR methods, I think the easiest way is to deploy the deep neural network for MFSR, but it needs the network training. With your great work, the code seems no need for network training, but for me, that is a huge work to convert your C# projects to the C++ version. In addition, there are a plenty of variables in your code (how could you manage so much variables in your brain?). I want to port your code on the registration part and super-resolution part.

I have installed the .NET Core 3.1 in the Jetson NX system. And I've compiled the .Net Core 3.1 version of the `managedCUDA`. There are many generated dll files with `.netCore.dll` postfixes. Can these dll files be copied to the Jetson NX system? I tried to run an example in `managedCUDA`, but there are several errors. 

![x](https://user-images.githubusercontent.com/43327429/113797893-aedb0a80-9784-11eb-9080-d21b9b821cdb.jpg)
