### ISSUE TITLE
System.DllNotFoundException：Unable to load DLL“nppisu64_10”: 

### ISSUE THREAD

**Issue by weilongMao** [kunzmi/ImageStackAlignator#25]
Hi Michael, Thanks for your helpful job.
My tutor gave me a 3060, but it does not support cuda10. So the error shown in the title appeared under cuda11. How can I update ImageStackAlignator with your latest version of ManagedCuda? 
Thanks again！

**Comment by kunzmi** [comment]
There are two things that you need to do:
- update all Nuget packages pointing to managedCuda 10 to the latest managedCuda 11.4 version (four packages in total: ManagedCuda-10 -> ManagedCuda-11, ManagedCuda-CUBLAS, ManagedCuda-CUFFT and ManagedCuda-NPP)
- Change on how the CUDA context is created in file ```ImagePresenterDX.xaml.cs``` line 202:

from 
```C#
_ctx = new CudaContext(cudaDevices[0], _device.ComPointer, CUCtxFlags.BlockingSync, CudaContext.DirectXVersion.D3D9);
```
to
```C#
// This device ID mess is necessary because ManagedCuda doesn't allow to create a
// PrimaryContext directly from a CUdevice (this should be changed, until then we need this hack)
int deviceCount = CudaContext.GetDeviceCount();
int deviceOrdinal = -1;
for (int id = 0; id < deviceCount; id++)
{
    if (CudaContext.GetCUdevice(id) == cudaDevices[0])
    {
        deviceOrdinal = id;
        break;
    }
}
if (deviceOrdinal < 0)
{
    throw new CudaException("Couldn't find corresponding device ordinal");
}

// Nvidia changed context behaviour in the CUFFT/CUBLAS/NPP libraries so that it
// is now mandatory to use a "PrimaryContext" and not a "CudaContext" as before:
_ctx = new PrimaryContext(deviceOrdinal);
// Calling SetCurrent() is necessary for a PrimaryContext to bind it to the current CPU thread:
_ctx.SetCurrent();
```

After these changes it should run normally.

Cheers,
Michael

**Comment by weilongMao** [comment]
Thanks for your in time reply!
