### ISSUE TITLE
Do quality analysis mentioned in Google's paper with TIFF and PNG photos

### ISSUE THREAD

**Issue by iKaHibi** [kunzmi/ImageStackAlignator#28]
Hi Michael, thanks for your code.
I want to run the quality analysis in Section 6.1 of Google's paper with your code, but the photo datasets they use (Kodak and McMaster) seems only offer tiff and png pictures.
Is there any way to accomplish the analysis, for example transforming TIFF to DNG or something?

**Comment by kunzmi** [comment]
Hi
I guess the simplest way would be to implement another ```RawFile``` derivated class, similar to ```PEFFile``` and ```DNGFile```. PEF and DNG-files are basically TIFF files and differ only in minor details, so a new generic TIFF-reader would be more or less a copy of ```PEFFile```.
Or use the standard .net image reading routines and only map the interface of ```RawFile``` accordingly.
Once having a class with the RawFile-interface reading standard images, the rest remains as is.

**Comment by iKaHibi** [comment]
> Hi I guess the simplest way would be to implement another `RawFile` derivated class, similar to `PEFFile` and `DNGFile`. PEF and DNG-files are basically TIFF files and differ only in minor details, so a new generic TIFF-reader would be more or less a copy of `PEFFile`. Or use the standard .net image reading routines and only map the interface of `RawFile` accordingly. Once having a class with the RawFile-interface reading standard images, the rest remains as is.

Ok, thank you very much!
