### ISSUE TITLE
Parameter tuning

### ISSUE THREAD

**Issue by mm93v** [kunzmi/ImageStackAlignator#3]
Hi

How do I adjust the parameter to remove haze with super-resolution enabled?
I follow the steps as you mentioned with the default setting. But the result has some artifacts and purple haze after pressing the "accumulate".

Super-resolution
[https://imgur.com/a/4OqWKAR](url)

Single frame zoom-in 
[https://imgur.com/a/7CcUfca](url)

You can download my dataset from here([https://reurl.cc/j77mNL](url)).

Thank you.

**Comment by kunzmi** [comment]
Your images have a blackLevel of 512 that was not taken into account in the accumulation step. I pushed a fix for that, now it should work.
I also saw that the noise model values of your images seem a bit low, you can see that the certainty mask especially for green channel is quite bad. Increase the value for noise model alpha a bit.

**Comment by mm93v** [comment]
The purple haze is been removed now.

Thank you for your promptly update!
