### ISSUE TITLE
Possibility of using .tiff images?

### ISSUE THREAD

**Issue by dhalnon** [kunzmi/ImageStackAlignator#30]
Is it possible to use .tiff images as inputs?

**Comment by kunzmi** [comment]
Depends on what you mean by .tiff images: Do you mean "normal" images with RGB channels or raw images with bayer pattern? If the latter, it should be easy to get it to run, .dng files are just tiff files with specific tags. On the other hand, if you mean "normal" images, then one would need to adapt the entire processing as the debayering step is a crucial component of the algorithm. It's not impossible but needs some work to be done.

**Comment by dhalnon** [comment]
Do you know a good way of verifying if the images are one vs the other? Sorry for the simple questions, image processing is something I'm having to catch up a lot on
