### ISSUE TITLE
Only RAW pictures can be selected as input, can I choose other formats, such as bmp? 

### ISSUE THREAD

**Issue by hzj020621** [kunzmi/ImageStackAlignator#5]

**Comment by hzj020621** [comment]
Only RAW pictures can be selected as input, can I choose other formats, such as bmp？

**Comment by hzj020621** [comment]
if can not selected .bmp images, where can i download the test images

**Comment by kunzmi** [comment]
No, the algorithm is made to debayer RAW images, why only RAW images can be used as input. Basically every mobile phone can shoot RAW these days, why I don't provide iamges.
