### ISSUE TITLE
any update on aligning CUDA versions?

### ISSUE THREAD

**Issue by alex-111-gh** [kunzmi/ImageStackAlignator#8]
Quick context:
This project requires 10.1 for building cuda kernels
Dependencies in Managed CUDA (NPP dlls specifically) rely on 10.0.
Latest published Managed CUDA is 10.0.

@kunzmi any update on bumping all of that to single CUDA version? Let's say 10.2? :)

**Comment by kunzmi** [comment]
There you go :)
