### ISSUE TITLE
do you think it has a chance to run in *nix?

### ISSUE THREAD

**Issue by alex-111-gh** [kunzmi/ImageStackAlignator#9]
Hi @kunzmi 
Do you think this project has a reasonable chance to run in mono  in linux?
One obvious requirement is that all directX stuff is stripped off.
How about managedCuda and other dependencies? Would they survive and stay functional in *nix (say Ubuntu)?

**Comment by kunzmi** [comment]
it is only the GUI with DirectX/WPF that binds it to Windows. ManagedCuda including all libraries runs perfectly on mono and .net Core on Linux: Stripping off all WPF components, this will run as is on Linux.

**Comment by alex-111-gh** [comment]
@kunzmi thanks for the feedback!
